"""Every event type the system can emit. All major actions create an event."""

from __future__ import annotations

from enum import StrEnum


class EventType(StrEnum):
    # system
    SYSTEM_STARTED = "SYSTEM_STARTED"
    SYSTEM_ERROR = "SYSTEM_ERROR"
    SETTINGS_UPDATED = "SETTINGS_UPDATED"
    # projects and conversations
    PROJECT_CREATED = "PROJECT_CREATED"
    PROJECT_UPDATED = "PROJECT_UPDATED"
    PROJECT_ARCHIVED = "PROJECT_ARCHIVED"
    CONVERSATION_CREATED = "CONVERSATION_CREATED"
    MESSAGE_CREATED = "MESSAGE_CREATED"
    # providers and usage
    PROVIDER_CONFIGURED = "PROVIDER_CONFIGURED"
    PROVIDER_REMOVED = "PROVIDER_REMOVED"
    PROVIDER_TESTED = "PROVIDER_TESTED"
    USAGE_RECORDED = "USAGE_RECORDED"
    BUDGET_WARNING = "BUDGET_WARNING"
    BUDGET_EXCEEDED = "BUDGET_EXCEEDED"
    # objectives and planning
    OBJECTIVE_CREATED = "OBJECTIVE_CREATED"
    PLAN_CREATED = "PLAN_CREATED"
    PLAN_EDITED = "PLAN_EDITED"
    PLAN_APPROVED = "PLAN_APPROVED"
    OBJECTIVE_STARTED = "OBJECTIVE_STARTED"
    OBJECTIVE_PAUSED = "OBJECTIVE_PAUSED"
    OBJECTIVE_RESUMED = "OBJECTIVE_RESUMED"
    OBJECTIVE_COMPLETED = "OBJECTIVE_COMPLETED"
    OBJECTIVE_FAILED = "OBJECTIVE_FAILED"
    OBJECTIVE_CANCELLED = "OBJECTIVE_CANCELLED"
    # tasks
    TASK_CREATED = "TASK_CREATED"
    TASK_STARTED = "TASK_STARTED"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_FAILED = "TASK_FAILED"
    TASK_CANCELLED = "TASK_CANCELLED"
    TASK_BLOCKED = "TASK_BLOCKED"
    TASK_RETRIED = "TASK_RETRIED"
    TASK_STATUS_CHANGED = "TASK_STATUS_CHANGED"
    # agents
    AGENT_CREATED = "AGENT_CREATED"
    AGENT_UPDATED = "AGENT_UPDATED"
    AGENT_STARTED = "AGENT_STARTED"
    AGENT_STEP = "AGENT_STEP"
    AGENT_COMPLETED = "AGENT_COMPLETED"
    AGENT_FAILED = "AGENT_FAILED"
    AGENT_CANCELLED = "AGENT_CANCELLED"
    AGENT_INTERRUPTED = "AGENT_INTERRUPTED"
    AGENT_RESUMED = "AGENT_RESUMED"
    AGENT_MESSAGE = "AGENT_MESSAGE"
    # review, verification, recovery
    REVIEW_COMPLETED = "REVIEW_COMPLETED"
    VERIFICATION_COMPLETED = "VERIFICATION_COMPLETED"
    RECOVERY_DECISION = "RECOVERY_DECISION"
    # tools and approvals
    TOOL_CALLED = "TOOL_CALLED"
    TOOL_COMPLETED = "TOOL_COMPLETED"
    TOOL_FAILED = "TOOL_FAILED"
    TOOL_DENIED = "TOOL_DENIED"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    APPROVAL_GRANTED = "APPROVAL_GRANTED"
    APPROVAL_DENIED = "APPROVAL_DENIED"
    APPROVAL_EDITED = "APPROVAL_EDITED"
    # artifacts and files
    ARTIFACT_CREATED = "ARTIFACT_CREATED"
    ARTIFACT_UPDATED = "ARTIFACT_UPDATED"
    FILE_WRITTEN = "FILE_WRITTEN"
    FILE_DELETED = "FILE_DELETED"
    CLIPBOARD_REQUEST = "CLIPBOARD_REQUEST"
    # memory
    MEMORY_CREATED = "MEMORY_CREATED"
    MEMORY_UPDATED = "MEMORY_UPDATED"
    MEMORY_DELETED = "MEMORY_DELETED"
    MEMORY_REJECTED = "MEMORY_REJECTED"
    MEMORY_COMPRESSED = "MEMORY_COMPRESSED"
    # workflows and scheduling
    WORKFLOW_CREATED = "WORKFLOW_CREATED"
    WORKFLOW_UPDATED = "WORKFLOW_UPDATED"
    WORKFLOW_STARTED = "WORKFLOW_STARTED"
    WORKFLOW_NODE_COMPLETED = "WORKFLOW_NODE_COMPLETED"
    WORKFLOW_COMPLETED = "WORKFLOW_COMPLETED"
    WORKFLOW_FAILED = "WORKFLOW_FAILED"
    SCHEDULE_CREATED = "SCHEDULE_CREATED"
    SCHEDULE_FIRED = "SCHEDULE_FIRED"
    # integrations
    INTEGRATION_CONFIGURED = "INTEGRATION_CONFIGURED"
    MCP_SERVER_STARTED = "MCP_SERVER_STARTED"
    MCP_SERVER_STOPPED = "MCP_SERVER_STOPPED"
    # security
    SECURITY_FLAG = "SECURITY_FLAG"
    POLICY_DENIED = "POLICY_DENIED"
    # notifications
    NOTIFICATION_CREATED = "NOTIFICATION_CREATED"
