"""orchestration

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-29 17:10:52.906479
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "objectives",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("project_id", sa.String(length=40), nullable=False),
        sa.Column("conversation_id", sa.String(length=40), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("run_mode", sa.String(length=20), nullable=False),
        sa.Column("execution_mode", sa.String(length=20), nullable=False),
        sa.Column("strategy", sa.JSON(), nullable=True),
        sa.Column("plan", sa.JSON(), nullable=True),
        sa.Column("attachments", sa.JSON(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error", sa.JSON(), nullable=True),
        sa.Column("budget", sa.JSON(), nullable=False),
        sa.Column("model", sa.String(length=300), nullable=True),
        sa.Column("private", sa.Boolean(), nullable=False),
        sa.Column("replan_count", sa.Integer(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_objectives")),
    )
    with op.batch_alter_table("objectives", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_objectives_project_id"), ["project_id"], unique=False)
        batch_op.create_index("ix_objectives_status", ["status"], unique=False)

    op.create_table(
        "tasks",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("objective_id", sa.String(length=40), nullable=False),
        sa.Column("project_id", sa.String(length=40), nullable=False),
        sa.Column("key", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=12), nullable=False),
        sa.Column("assigned_agent", sa.String(length=60), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("inputs", sa.JSON(), nullable=False),
        sa.Column("outputs", sa.JSON(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("approval_required", sa.Boolean(), nullable=False),
        sa.Column("optional", sa.Boolean(), nullable=False),
        sa.Column("review", sa.Boolean(), nullable=False),
        sa.Column("round", sa.Integer(), nullable=False),
        sa.Column("parent_task_id", sa.String(length=40), nullable=True),
        sa.Column("run_id", sa.String(length=40), nullable=True),
        sa.Column("resume", sa.Boolean(), nullable=False),
        sa.Column("error", sa.JSON(), nullable=True),
        sa.Column("position", sa.JSON(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["objective_id"],
            ["objectives.id"],
            name=op.f("fk_tasks_objective_id_objectives"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
        sa.UniqueConstraint("objective_id", "key", name="uq_tasks_objective_key"),
    )
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tasks_objective_id"), ["objective_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_tasks_project_id"), ["project_id"], unique=False)
        batch_op.create_index("ix_tasks_status", ["status"], unique=False)

    op.create_table(
        "task_dependencies",
        sa.Column("task_id", sa.String(length=40), nullable=False),
        sa.Column("depends_on_id", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["depends_on_id"],
            ["tasks.id"],
            name=op.f("fk_task_dependencies_depends_on_id_tasks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_task_dependencies_task_id_tasks"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("task_id", "depends_on_id", name=op.f("pk_task_dependencies")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task_dependencies")
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_index("ix_tasks_status")
        batch_op.drop_index(batch_op.f("ix_tasks_project_id"))
        batch_op.drop_index(batch_op.f("ix_tasks_objective_id"))

    op.drop_table("tasks")
    with op.batch_alter_table("objectives", schema=None) as batch_op:
        batch_op.drop_index("ix_objectives_status")
        batch_op.drop_index(batch_op.f("ix_objectives_project_id"))

    op.drop_table("objectives")
    # ### end Alembic commands ###
