/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/budgets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Budgets */
        get: operations["get_budgets"];
        /** Put Budgets */
        put: operations["put_budgets"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Messages */
        get: operations["list_messages"];
        put?: never;
        /** Post Message */
        post: operations["post_message"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Events
         * @description SSE feed. Resume with ``Last-Event-ID`` (or ``after``) to replay without gaps.
         */
        get: operations["stream_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verify Events
         * @description Recompute the audit-log hash chain (all chains, or one project's).
         */
        get: operations["verify_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ping
         * @description Unauthenticated liveness probe. Deliberately reveals nothing else.
         */
        get: operations["ping"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All Models */
        get: operations["all_models"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notifications */
        get: operations["list_notifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Read All */
        post: operations["read_all"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/unread-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Unread Count */
        get: operations["unread_count"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{notification_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Read */
        post: operations["mark_read"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects"];
        put?: never;
        /** Create Project */
        post: operations["create_project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Project */
        patch: operations["update_project"];
        trace?: never;
    };
    "/api/projects/{project_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Project */
        post: operations["archive_project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Conversations */
        get: operations["list_conversations"];
        put?: never;
        /** Create Conversation */
        post: operations["create_conversation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unarchive Project */
        post: operations["unarchive_project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Providers */
        get: operations["list_providers"];
        put?: never;
        /** Create Provider */
        post: operations["create_provider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers/kinds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Provider Kinds */
        get: operations["provider_kinds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers/{provider_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Provider */
        get: operations["get_provider"];
        put?: never;
        post?: never;
        /** Delete Provider */
        delete: operations["delete_provider"];
        options?: never;
        head?: never;
        /** Update Provider */
        patch: operations["update_provider"];
        trace?: never;
    };
    "/api/providers/{provider_id}/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Provider Models */
        get: operations["provider_models"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers/{provider_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Provider */
        post: operations["test_provider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routing/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Route
         * @description What would the router pick for this kind of task? Never calls a model.
         */
        post: operations["preview_route"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routing/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rules */
        get: operations["get_rules"];
        /** Put Rules */
        put: operations["put_rules"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Settings */
        patch: operations["update_settings"];
        trace?: never;
    };
    "/api/usage/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Usage Summary */
        get: operations["usage_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Budgets
         * @description Limits are optional. Cost limits count only calls whose price is known; token limits count all.
         */
        Budgets: {
            /** Daily Tokens */
            daily_tokens?: number | null;
            /** Daily Usd */
            daily_usd?: number | null;
            /**
             * Expensive Call Usd
             * @default 0.5
             */
            expensive_call_usd?: number | null;
            /**
             * Hard Stop
             * @default true
             */
            hard_stop?: boolean;
            /** Monthly Tokens */
            monthly_tokens?: number | null;
            /** Monthly Usd */
            monthly_usd?: number | null;
            /** Per Agent Monthly Usd */
            per_agent_monthly_usd?: {
                [key: string]: number;
            };
            /** Per Project Monthly Usd */
            per_project_monthly_usd?: {
                [key: string]: number;
            };
            /**
             * Warn At Fraction
             * @default 0.8
             */
            warn_at_fraction?: number;
        };
        /** ChainVerification */
        ChainVerification: {
            /** Chains Checked */
            chains_checked: number;
            /** Detail */
            detail?: string | null;
            /** Events Checked */
            events_checked: number;
            /** First Bad Seq */
            first_bad_seq?: number | null;
            /** Ok */
            ok: boolean;
        };
        /** ConnectionTestOut */
        ConnectionTestOut: {
            /** Detail */
            detail: string;
            /** Error Code */
            error_code?: string | null;
            /** Latency Ms */
            latency_ms: number;
            /** Models Found */
            models_found?: number | null;
            /** Ok */
            ok: boolean;
        };
        /** ConversationCreate */
        ConversationCreate: {
            /**
             * Title
             * @default New conversation
             */
            title?: string;
        };
        /** ConversationOut */
        ConversationOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * EventRecord
         * @description One immutable entry of the audit trail.
         */
        EventRecord: {
            /**
             * Actor
             * @default system
             */
            actor?: string;
            /** Agent Id */
            agent_id?: string | null;
            /** Hash */
            hash: string;
            /** Id */
            id: string;
            /** Objective Id */
            objective_id?: string | null;
            /**
             * Payload
             * @default {}
             */
            payload?: {
                [key: string]: unknown;
            };
            /** Prev Hash */
            prev_hash: string;
            /** Project Id */
            project_id?: string | null;
            /** Run Id */
            run_id?: string | null;
            /** Seq */
            seq: number;
            /** Task Id */
            task_id?: string | null;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Type */
            type: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthCheckResult */
        HealthCheckResult: {
            /** Data */
            data?: {
                [key: string]: unknown;
            };
            /**
             * Detail
             * @default
             */
            detail?: string;
            /** Label */
            label: string;
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded" | "down" | "unavailable";
        };
        /** HealthReport */
        HealthReport: {
            /** Checks */
            checks: components["schemas"]["HealthCheckResult"][];
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded" | "down" | "unavailable";
            /** Version */
            version: string;
        };
        /** MessageCreate */
        MessageCreate: {
            /** Content */
            content: string;
        };
        /** MessageOut */
        MessageOut: {
            /** Agent Id */
            agent_id: string | null;
            /** Content */
            content: string;
            /** Conversation Id */
            conversation_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Meta */
            meta: {
                [key: string]: unknown;
            };
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant" | "agent" | "system";
        };
        /** ModelOut */
        ModelOut: {
            /** Context Length */
            context_length: number | null;
            /** Display Name */
            display_name: string | null;
            /** Id */
            id: string;
            /** Input Cost Per Mtok */
            input_cost_per_mtok: number | null;
            /** Local */
            local: boolean;
            /** Output Cost Per Mtok */
            output_cost_per_mtok: number | null;
            /** Provider Id */
            provider_id: string;
            /** Provider Name */
            provider_name: string;
            /** Ref */
            ref: string;
            /** Tier */
            tier: ("fast" | "balanced" | "strong") | null;
        };
        /** ModelOverride */
        ModelOverride: {
            /** Context Length */
            context_length?: number | null;
            price?: components["schemas"]["ModelPrice"] | null;
            /** Supports Reasoning */
            supports_reasoning?: boolean | null;
            /** Supports Vision */
            supports_vision?: boolean | null;
            /** Tier */
            tier?: ("fast" | "balanced" | "strong") | null;
        };
        /**
         * ModelPrice
         * @description USD per million tokens. Set by the user; unknown prices stay unset (never guessed).
         */
        ModelPrice: {
            /** Input */
            input: number;
            /** Output */
            output: number;
        };
        /** NotificationOut */
        NotificationOut: {
            /** Body */
            body: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Project Id */
            project_id: string | null;
            /** Read At */
            read_at: string | null;
            /** Ref */
            ref: {
                [key: string]: unknown;
            };
            /** Title */
            title: string;
        };
        /**
         * PermissionLevel
         * @enum {string}
         */
        PermissionLevel: "cautious" | "balanced" | "permissive";
        /** ProjectCreate */
        ProjectCreate: {
            /**
             * Description
             * @default
             */
            description?: string;
            /**
             * Icon
             * @default folder
             */
            icon?: string;
            /** Name */
            name: string;
            settings?: components["schemas"]["ProjectSettings"];
        };
        /** ProjectOut */
        ProjectOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string;
            /** Icon */
            icon: string;
            /** Id */
            id: string;
            /** Is Demo */
            is_demo: boolean;
            /** Name */
            name: string;
            settings: components["schemas"]["ProjectSettings"];
            /** Slug */
            slug: string;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "archived";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProjectSettings */
        ProjectSettings: {
            /** Allowed Domains */
            allowed_domains?: string[];
            /** Linked Folders */
            linked_folders?: string[];
            /** Monthly Budget Usd */
            monthly_budget_usd?: number | null;
            permission_level?: components["schemas"]["PermissionLevel"] | null;
        };
        /** ProjectUpdate */
        ProjectUpdate: {
            /** Description */
            description?: string | null;
            /** Icon */
            icon?: string | null;
            /** Name */
            name?: string | null;
            settings?: components["schemas"]["ProjectSettings"] | null;
        };
        /** ProviderCreate */
        ProviderCreate: {
            /** Api Key */
            api_key?: string | null;
            /** Base Url */
            base_url?: string | null;
            /** Default Model */
            default_model?: string | null;
            /**
             * Enabled
             * @default true
             */
            enabled?: boolean;
            /**
             * Kind
             * @enum {string}
             */
            kind: "anthropic" | "openai" | "gemini" | "ollama" | "lmstudio" | "openai_compatible" | "demo";
            /** Name */
            name: string;
            options?: components["schemas"]["ProviderOptions"];
        };
        /** ProviderKindInfo */
        ProviderKindInfo: {
            /** Default Base Url */
            default_base_url: string | null;
            /** Help */
            help: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "anthropic" | "openai" | "gemini" | "ollama" | "lmstudio" | "openai_compatible" | "demo";
            /** Label */
            label: string;
            /** Local */
            local: boolean;
            /** Needs Key */
            needs_key: boolean;
        };
        /** ProviderOptions */
        ProviderOptions: {
            /** Models */
            models?: {
                [key: string]: components["schemas"]["ModelOverride"];
            };
            /**
             * Structured Mode
             * @default json_schema
             * @enum {string}
             */
            structured_mode?: "json_schema" | "json_object" | "prompt";
        };
        /**
         * ProviderOut
         * @description Never contains the key. ``has_key``/``key_hint`` let the UI show that one is stored.
         */
        ProviderOut: {
            /** Base Url */
            base_url: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Default Model */
            default_model: string | null;
            /** Enabled */
            enabled: boolean;
            /** Has Key */
            has_key: boolean;
            /** Id */
            id: string;
            /** Is Local */
            is_local: boolean;
            /** Key Hint */
            key_hint: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "anthropic" | "openai" | "gemini" | "ollama" | "lmstudio" | "openai_compatible" | "demo";
            /** Last Test At */
            last_test_at: string | null;
            /** Last Test Error */
            last_test_error: string | null;
            /** Last Test Ok */
            last_test_ok: boolean | null;
            /** Name */
            name: string;
            options: components["schemas"]["ProviderOptions"];
        };
        /** ProviderUpdate */
        ProviderUpdate: {
            /** Api Key */
            api_key?: string | null;
            /** Base Url */
            base_url?: string | null;
            /** Default Model */
            default_model?: string | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Name */
            name?: string | null;
            options?: components["schemas"]["ProviderOptions"] | null;
        };
        /** RoutePreview */
        RoutePreview: {
            /** Fallbacks */
            fallbacks: string[];
            /** Primary */
            primary: string;
            /** Reason */
            reason: string;
        };
        /** RoutePreviewRequest */
        RoutePreviewRequest: {
            /** Fallback Models */
            fallback_models?: string[];
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens?: number;
            /** Preferred Model */
            preferred_model?: string | null;
            /**
             * Private
             * @default false
             */
            private?: boolean;
            /**
             * Task Class
             * @default general
             * @enum {string}
             */
            task_class?: "formatting" | "coding" | "planning" | "long_document" | "general";
        };
        /** RoutingPrefer */
        RoutingPrefer: {
            /** Local */
            local?: boolean | null;
            /** Model */
            model?: string | null;
            /** Provider Id */
            provider_id?: string | null;
            /** Tier */
            tier?: ("fast" | "balanced" | "strong") | null;
        };
        /** RoutingRule */
        RoutingRule: {
            /** Name */
            name: string;
            prefer: components["schemas"]["RoutingPrefer"];
            when?: components["schemas"]["RoutingWhen"];
        };
        /** RoutingRules */
        RoutingRules: {
            /** Rules */
            rules?: components["schemas"]["RoutingRule"][];
        };
        /** RoutingWhen */
        RoutingWhen: {
            /** Min Input Tokens */
            min_input_tokens?: number | null;
            /** Private */
            private?: boolean | null;
            /** Task Class */
            task_class?: ("formatting" | "coding" | "planning" | "long_document" | "general") | null;
        };
        /** UsageGroup */
        UsageGroup: {
            /** Calls */
            calls: number;
            /** Cost Usd */
            cost_usd: number;
            /** Input Tokens */
            input_tokens: number;
            /** Key */
            key: string;
            /** Output Tokens */
            output_tokens: number;
            /** Unknown Cost Calls */
            unknown_cost_calls: number;
        };
        /** UsageSummary */
        UsageSummary: {
            /** Days */
            days: number;
            /** Group By */
            group_by: string;
            /** Groups */
            groups: components["schemas"]["UsageGroup"][];
            /** Total Calls */
            total_calls: number;
            /** Total Cost Usd */
            total_cost_usd: number;
            /** Total Tokens */
            total_tokens: number;
            /** Unknown Cost Calls */
            unknown_cost_calls: number;
        };
        /** UserSettingsOut */
        UserSettingsOut: {
            default_permission_level: components["schemas"]["PermissionLevel"];
            /** Display Name */
            display_name: string;
            /** Onboarding Completed */
            onboarding_completed: boolean;
            /** Preferences */
            preferences: {
                [key: string]: unknown;
            };
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Workspace Root */
            workspace_root: string;
        };
        /** UserSettingsUpdate */
        UserSettingsUpdate: {
            default_permission_level?: components["schemas"]["PermissionLevel"] | null;
            /** Display Name */
            display_name?: string | null;
            /** Onboarding Completed */
            onboarding_completed?: boolean | null;
            /** Preferences */
            preferences?: {
                [key: string]: unknown;
            } | null;
            /** Workspace Root */
            workspace_root?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_budgets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Budgets"];
                };
            };
        };
    };
    put_budgets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Budgets"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Budgets"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_messages: {
        parameters: {
            query?: {
                after_id?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_message: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events: {
        parameters: {
            query?: {
                project_id?: string | null;
                objective_id?: string | null;
                task_id?: string | null;
                run_id?: string | null;
                /** @description Comma-separated event types */
                types?: string | null;
                after_seq?: number;
                limit?: number;
                newest_first?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events: {
        parameters: {
            query?: {
                project_id?: string | null;
                objective_id?: string | null;
                task_id?: string | null;
                run_id?: string | null;
                types?: string | null;
                after?: number | null;
            };
            header?: {
                "last-event-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_events: {
        parameters: {
            query?: {
                project_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChainVerification"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthReport"];
                };
            };
        };
    };
    ping: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    all_models: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelOut"][];
                };
            };
        };
    };
    list_notifications: {
        parameters: {
            query?: {
                unread_only?: boolean;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_all: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
        };
    };
    unread_count: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
        };
    };
    mark_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notification_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects: {
        parameters: {
            query?: {
                status_filter?: ("active" | "archived") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_conversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unarchive_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_providers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderOut"][];
                };
            };
        };
    };
    create_provider: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    provider_kinds: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderKindInfo"][];
                };
            };
        };
    };
    get_provider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_provider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_provider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    provider_models: {
        parameters: {
            query?: {
                refresh?: boolean;
            };
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_provider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionTestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_route: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoutePreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutePreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutingRules"];
                };
            };
        };
    };
    put_rules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoutingRules"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutingRules"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSettingsOut"];
                };
            };
        };
    };
    update_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserSettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    usage_summary: {
        parameters: {
            query?: {
                days?: number;
                group_by?: "model" | "provider" | "agent" | "project" | "day" | "purpose";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
