import type { components } from "./api";

export type { components, operations, paths } from "./api";
export * from "./events";

type S = components["schemas"];

export type Project = S["ProjectOut"];
export type ProjectCreate = S["ProjectCreate"];
export type ProjectUpdate = S["ProjectUpdate"];
export type ProjectSettings = S["ProjectSettings"];
export type Conversation = S["ConversationOut"];
export type Message = S["MessageOut"];
export type UserSettings = S["UserSettingsOut"];
export type UserSettingsUpdate = S["UserSettingsUpdate"];
export type Notification = S["NotificationOut"];
export type HealthReport = S["HealthReport"];
export type HealthCheck = S["HealthCheckResult"];
export type PermissionLevel = S["PermissionLevel"];
export type ChainVerification = S["ChainVerification"];
export type Provider = S["ProviderOut"];
export type ProviderCreate = S["ProviderCreate"];
export type ProviderUpdate = S["ProviderUpdate"];
export type ProviderKindInfo = S["ProviderKindInfo"];
export type ProviderKind = S["ProviderKindInfo"]["kind"];
export type ModelOut = S["ModelOut"];
export type ConnectionTest = S["ConnectionTestOut"];
export type UsageSummary = S["UsageSummary"];
export type UsageGroup = S["UsageGroup"];
export type Budgets = S["Budgets"];

export type Agent = S["AgentDefinition"];
export type AgentCreate = S["AgentCreate"];
export type AgentUpdate = S["AgentUpdate"];
export type AgentRun = S["AgentRunOut"];
export type AgentRunRequest = S["AgentRunRequest"];
export type RunDetail = S["RunDetail"];
export type RunStatus = S["RunStatus"];
export type Approval = S["ApprovalOut"];
export type ApprovalDecision = S["ApprovalDecision"];
export type SessionGrant = S["SessionGrantOut"];
export type Tool = S["ToolOut"];
export type ToolCall = S["ToolCallOut"];
export type RiskLevel = S["RiskLevel"];
export type Artifact = S["ArtifactOut"];
export type ArtifactVersion = S["ArtifactVersionOut"];
export type ArtifactContent = S["ArtifactContent"];
export type FileEntry = S["FileEntryOut"];
export type FileContent = S["FileContentOut"];

export type Objective = S["ObjectiveOut"];
export type ObjectiveCreate = S["ObjectiveCreate"];
export type ObjectiveDetail = S["ObjectiveDetail"];
export type ObjectiveStatus = S["ObjectiveStatus"];
export type TaskNode = S["TaskOut"];
export type TaskStatus = S["TaskStatus"];
export type PlanTask = S["PlanTask"];
export type PlanEdit = S["PlanEdit"];
export type AgentMessage = S["AgentMessage"];

export type MemoryItem = S["MemoryItemOut"];
export type MemoryCreate = S["MemoryCreate"];
export type MemoryUpdate = S["MemoryUpdate"];
export type MemoryHit = S["MemoryHit"];
export type MemoryStats = S["MemoryStats"];
export type MemorySource = S["MemorySource"];
export type ScoreBreakdown = S["ScoreBreakdown"];
export type CompressionReport = S["CompressionReport"];
export type ContextReport = S["ContextReport"];
export type ContextEntry = S["ContextEntry"];
export type SearchResults = S["SearchResults"];
export type SearchHit = S["SearchHit"];
export type SearchKind = S["SearchHit"]["kind"];

export type Workflow = S["WorkflowOut"];
export type WorkflowCreate = S["WorkflowCreate"];
export type WorkflowUpdate = S["WorkflowUpdate"];
export type WorkflowDefinition = S["WorkflowDefinition"];
export type WorkflowNode = S["WorkflowNode"];
export type WorkflowEdge = S["WorkflowEdge"];
export type WorkflowInput = S["WorkflowInput"];
export type WorkflowNodeType = S["WorkflowNode"]["type"];
export type WorkflowVersion = S["WorkflowVersionOut"];
export type WorkflowRun = S["WorkflowRunOut"];
export type WorkflowRunDetail = S["WorkflowRunDetail"];
export type WorkflowRunStatus = S["WorkflowRunStatus"];
export type NodeState = S["NodeState"];
export type ValidationReport = S["ValidationReport"];
export type ValidationIssue = S["ValidationIssue"];
export type Schedule = S["ScheduleOut"];
export type ScheduleCreate = S["ScheduleCreate"];
export type ScheduleUpdate = S["ScheduleUpdate"];
export type CronPreview = S["CronPreview"];
